### ISSUE TITLE
database.yml location config

### ISSUE THREAD

**Issue by noazark** [pat/thinking-sphinx#249]
Setting database_yml_file in my sphinx.yml doesn't seem to be having any effect on where the configuration generator looks for my database config. I'm installing my gem from the source, and it looks as if it should work. Here's my sphinx.yml:

```
development:
  enable_star: 1
  min_infix_len: 1
  config_file: /path/to/shared/config/sphinx.conf
  database_yml_file: /path/to/shared/config/database.yml
  pid_file: /path/to/shared/tmp/searchd.pid
  searchd_file_path: /path/to/shared/db/sphinx
```

In configuration.rb, parse_config looks like it will simply iterate over the settings above and set the corresponding attribute. But it's not working with database_yml_file.
