### ISSUE TITLE
min_infix_len is ignored in :configure

### ISSUE THREAD

**Issue by excalq** [pat/thinking-sphinx#444]
I have observed that no matter what value I configure for _min_infix_len_ in the yml config, running rake thinking_sphinx:configure always generates a conf file with a value of "3". I'm unable to resolve this issue so far.

sphinx.yml:

```
staging:
  config_file: /data/ourapp/current/config/sphinx/staging.sphinx.conf
  ...
  min_infix_len: 1
```

File config/sphinx/staging.sphinx.conf:

```
index movie_core
{
  source = movie_core_0
  path = /var/log/engineyard/sphinx/ourapp/indexes/movie_core
  charset_type = utf-8
  min_infix_len = 3
}
```
