### ISSUE TITLE
Duplication of listen parameter in *.sphinx.conf

### ISSUE THREAD

**Issue by me-kirill** [pat/thinking-sphinx#478]
When I use configuration file thinking_sphinx.yml and do rake ts:configure there are duplication in generated config:

```
searchd
{
   listen = 127.0.0.1:9301
   listen = 127.0.0.1:9301:mysql41
...
}
```

My yml config is simple:

```
development:
  port: 9301
  morphology: 
    - stem_enru
    - soundex
  mem_limit: 128M
  max_matches: 10000
```
