### ISSUE TITLE
Multiple addresses in thinking_sphinx.yml ?

### ISSUE THREAD

**Issue by thoughtpunch** [pat/thinking-sphinx#529]
The documentation shows specifying the address of the Sphinx host like so...

```
production:
  address: 10.0.0.4
  mysql41: 3200
```

Is it possible to specify multiple issues like so?

```
production:
  address:
  - 10.0.0.4
  - 10.0.0.5
  mysql41: 3200
```
