### ISSUE TITLE
how to specify port for listen in searchd block through config/sphinx.yml?

### ISSUE THREAD

**Issue by milushov** [pat/thinking-sphinx#596]
Hello Pat, i use thinking-sphinx version 2 and I need to set up sphinx for several environments, I'am trying like this:

config/sphinx.yml:

``` yaml
development:
  port: 9377

alpha:
  port: 9312

staging:
  port: 9313

production:
  port: 9314
```

But, when i invoke `rake ts:conf` for test purposes and check `config/development.sphinx.conf` file I see the same config as before with old port..

```
> cat config/development.sphinx.conf                                                                                                                                                                                                         
indexer
{
}

searchd
{
  listen = 127.0.0.1:9312
...
```
