### ISSUE TITLE
star is not working properly

### ISSUE THREAD

**Issue by chebyte** [pat/thinking-sphinx#714]
hi guys I have a problem with star, I have this index

```
ThinkingSphinx::Index.define :client, :with => :active_record, :delta => ThinkingSphinx::Deltas::SidekiqDelta do
  indexes(person.ssn, :as => :ssn)
end
```

and then in the console I run this cmd

```
Client.search("396486022", star: true).map{|a| a.person.ssn}
```

and it should return just one result but returns 2

```
["100546725", "396486022"]
```

why return this one `100546725` when I'm searching by `*396486022*`

my thinking sphinx yml is

```
development:
  mem_limit: 1024M
  64bit_timestamps: true
  enable_star: true
  min_infix_len: 4
```

@pat  any ideas?
