### ISSUE TITLE
Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (111)

### ISSUE THREAD

**Issue by bsodmike** [pat/thinking-sphinx#813]
Hi @pat,

I'm hoping you'd be able to point me in the right direction.  My config,

```
development:
  port: 9311
  html_strip: 1
  morphology: stem_en
test:
  port: 9313
  html_strip: 1
  morphology: stem_en
staging:
  port: 9319
  html_strip: 1
  bin_path: /usr/bin/
  morphology: stem_en
production:
  port: 9319
  html_strip: 1
  bin_path: /usr/bin/
  morphology: stem_en
```

Snippet from the config,

```
searchd
{
  listen = 127.0.0.1:9306:mysql41
```

Did a quick test,

```
mysql -h 127.0.0.1 -u root -p
Enter password:
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
```

Curious thing is we've got a couple other apps in our Chef stack and mysql responds the same for all of them, yet older versions of TS are running fine.  Unfortunately, these are also Rails 2x apps, and the one I'm having trouble with is our first Rails 4 app (in this stack).

Thanks!
Best M.

**Comment by kalashnikovisme** [comment]
@pat thanks! ```rake ts:configure ts:restart``` helped!

**Comment by dwickwire** [comment]
Hello, I know this issue is closed but I'm still experiencing it.  I've got a cron job running a `ts:rebuild` for me every 15 minutes.  Periodically, yet always at the same time as the cron rebuild I'm encountering a ThinkingSphinx::ConnectionError.  Note, my app and DB are on different hosts.

Here's the error,
>
ThinkingSphinx::ConnectionError (Error connecting to Sphinx via the MySQL protocol. Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (111)

Here's my thinking_sphinx yaml:

```yaml
production:
  address: 127.0.0.1
  mysql41: 9312
  sql_host: my.other.host
  sql_port: mysql41
  pid_file: /opt/run/my-app/searchd.pid
  searchd_file_path: /opt/data/my-app/sphinx/data
  indices_location: /opt/data/my-app/sphinx/data
  configuration_file: /opt/data/my-app/sphinx/production.sphinx.conf
  max_matches: 1000000
  quiet_deltas: true
  mem_limit: 512M

test: &TEST
  mysql41: 9307
  sql_port: mysql41
  searchd_file_path: tmp/sphinx/test/data
  indices_location: tmp/sphinx/test/data
  configuration_file: tmp/sphinx/test.sphinx.conf

cucumber:
  <<: *TEST
```

This seemed to become an issue ever since I upgraded from Rails 2 to Rails 3.2 and TS v3.  I tried avoiding this issue by upgrading to TS 3.1.4 but since I'm on Rails 3.2 and need polymorphic associations I can't use TS 3.1.4 until I'm on Rails 4, not that I'm sure that would resolve this anyway.

Is there something wrong with my config here or is this a bug on TS?  Or, is upgrading to Rails 4 and TS 3.1.4 the only way here?
