### ISSUE TITLE
Support for absolutisation of relative paths in configuration

### ISSUE THREAD

**Issue by lloeki** [pat/thinking-sphinx#816]
While it is extremely convenient to set paths as relative in `thinking_sphinx.ml`, some paths are better set as absolute in the generated Sphinx configuration.

There is also a particular case of unix sockets, where it is _required_ by both Sphinx and Riddle that a socket path be absolute, else it'll be tentatively handled as a DNS name.

Thinking Sphinx is aware of the application root/framework path and `ThinkingSphinx::Configuration` even has a `#real_path` method to automatically make a given relative path absolute from the app root.

The logic I implemented is as follows: for a given, known set of configuration keys that can contain paths, detect if:
- it is a path (contains `/`, heuristic for unix vs tcp socket)
- the path is relative (does not start with `/`)

and subsequently make it absolute.

The core of the logic is visible in the following monkey patch:

``` ruby
# config/initializers/absolute_sphinx.rb
class ThinkingSphinx::Configuration < Riddle::Configuration
  def apply_sphinx_settings!
    sphinx_sections.each do |object|
      settings.each do |key, value|
        next unless object.class.settings.include?(key.to_sym)

        # HACK: substitution logic
        value = real_path(value).to_s if %w{pid_file listen address}.include?(key) && value != nil && value.index('/') != nil && value.index('/') != 0 

        object.send("#{key}=", value)
      end
    end
  end
end
```

This allows me to write the following unified YAML that works in production and development, is compatible with Procfiles, and allows multiple independent deployed instances server-side:

``` yaml
common: &default
    indexed_models:
        - Article
        - Author
    enable_star: 1
    min_prefix_len: 3
    configuration_file: config/sphinx.conf
    pid_file: tmp/pids/sphinx.pid
    listen: tmp/pids/sphinx.sock:mysql2
    address: tmp/pids/sphinx.sock

development:
    <<: *default

test:
    <<: *default

staging:
    <<: *default

production:
    <<: *default
```

And here's an example unified Procfile that works both in development and in production (together with supervisord):

```
web:    bundle exec unicorn -c config/unicorn.rb
worker: bundle exec sidekiq
search: searchd --nodetach --config config/sphinx.conf
```
