### ISSUE TITLE
Star search

### ISSUE THREAD

**Issue by pioz** [pat/thinking-sphinx#853]
I'm use Thinking Sphinx (v3.1.1) with real time indexes.
 In my `thinking_sphinx.yml`:

```
development:
  dict: keywords
  enable_star: true
  min_prefix_len: 2
```

And search with:

```
User.search('enri', star: true)
```

The results are rights, for example if I search a user with name 'Enrico' with query string 'enri', I get the user.

But if I remove `min_prefix_len: 2` from `thinking_sphinx.yml` the star search no longer works.
