### ISSUE TITLE
FATAL: bind() failed on 127.0.0.1: Address already in use

### ISSUE THREAD

**Issue by vicovictor** [pat/thinking-sphinx#857]
Using Rails 3.2.17, Sphinx 2.2.4-id64-beta (r4797), thinking-sphinx (3.0.6) on a fresh VPS. When I try to run `RAILS_ENV=production bundle exec rake ts:regenerate`, I got the following. Initially my `config/thinking_sphinx.yml` port was set to 9312, but I changed it to `9306` after checking `sphinx.conf`. I just couldn't regenerate and start thinking_sphinx. Please advice. Thanks.

```
** Invoke ts:regenerate (first_time)
** Invoke ts:stop (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute ts:stop
searchd is not currently running.
Stopped searchd daemon (pid: ).
** Invoke ts:clear (first_time)
** Invoke environment 
** Execute ts:clear
** Invoke ts:configure (first_time)
** Invoke environment 
** Execute ts:configure
Generating configuration to /home/deployer/abc/shared/config/production.sphinx.conf
** Invoke ts:start (first_time)
** Invoke environment 
** Execute ts:start
Failed to start searchd daemon. Check /home/deployer/abc/shared/log/production.searchd.log.
Failed to start searchd. Check the log files for more information.
** Invoke ts:generate (first_time)
** Invoke environment 
** Execute ts:generate
Generating index files for shop_core
rake aborted!
ThinkingSphinx::SphinxError: no such index 'shop_core'
```

/etc/sphinxsearch/sphinx.conf:

```
searchd
{
  listen                  = 9312
  listen                  = 9306:mysql41
  ...
}
```

config/thinking_sphinx.yml:

```
global: &GLOBAL
  utf8: true
  ...
production:
  <<: *GLOBAL
  pid_file: /home/deployer/abc/shared/pids/searchd.pid
  indices_location: /home/deployer/abc/shared/db/sphinx
  configuration_file: /home/deployer/abc/shared/config/production.sphinx.conf
  mysql41: 9306
  mem_limit: 512M
```

production.searchd.log

```
[Wed Nov 26 02:24:41.104 2014] [24044] Child process 24045 has been forked
[Wed Nov 26 02:24:41.105 2014] [24045] listening on 127.0.0.1:9306
[Wed Nov 26 02:24:41.105 2014] [24045] bind() failed on 127.0.0.1, retrying...
[Wed Nov 26 02:24:44.106 2014] [24045] bind() failed on 127.0.0.1, retrying...
...
[Wed Nov 26 02:25:17.141 2014] [24045] FATAL: bind() failed on 127.0.0.1: Address already in use
[Wed Nov 26 02:25:17.144 2014] [24044] Child process 24045 has been finished, exit code 1. Watchdog finishes also. Good bye!
```
