### ISSUE TITLE
Search with one character do not work

### ISSUE THREAD

**Issue by pioz** [pat/thinking-sphinx#865]
I'm use Thinking Sphinx v3.1.1 and Sphinx v2.2.4  with real time indexes.
In my `thinking_sphinx.yml`:

```
development:
  dict: keywords
  enable_star: true
  min_infix_len: 1
```

My index:

```
ThinkingSphinx::Index.define :user, with: :real_time do
  indexes first_name
  indexes last_name
end
```

I've a user in my database `User.create(first_name: 'Enrico', last_name: 'Pilotto')`

If I search with:

```
User.search('enri pi')
```

I get the user, but if I search with

```
User.search('enri p')
```

I get no results. Seems that the search with one character don't work.
Any idea?
