### ISSUE TITLE
ThinkingSphinx::ConnectionError with binlog files not being cleaned up

### ISSUE THREAD

**Issue by dwickwire** [pat/thinking-sphinx#947]
I'm having a peculiar issue which is preventing my tests from passing.  When I run my specs, I consistently get an error `ThinkingSphinx::ConnectionError` which is similar to https://github.com/pat/thinking-sphinx/issues/813 but I think the culprit is different in this case.  

##### Here's how I know to reproduce it, I start by running a successful test:
```shell
production@vagrant:/opt/rails/production/current$ bundle exec rspec spec/controllers/contributors_controller_spec.rb 
** [Raven] Raven 0.13.3 ready to catch errors
...........................

Finished in 8.14 seconds (files took 19.79 seconds to load)
27 examples, 0 failures
```

##### Then I run a normal `ts:rebuild` for my development environment, to do dev work:
```shell
production@vagrant:/opt/rails/production/current$ bundle exec rake ts:rebuild
** [Raven] Raven 0.13.3 ready to catch errors
Stopped searchd daemon (pid: 3548).
Generating configuration to /opt/data/production-schedule/sphinx/development.sphinx.conf
Sphinx 2.0.4-id64-release (r3135)
Copyright (c) 2001-2012, Andrew Aksyonoff
Copyright (c) 2008-2012, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/opt/data/production-schedule/sphinx/development.sphinx.conf'...
indexing index 'contributor_core'...
collected 2749 docs, 0.1 MB
sorted 0.4 Mhits, 100.0% done
total 2749 docs, 120605 bytes
total 0.103 sec, 1163186 bytes/sec, 26512.99 docs/sec
indexing index 'contributor_delta'...
collected 0 docs, 0.0 MB
total 0 docs, 0 bytes
total 0.001 sec, 0 bytes/sec, 0.00 docs/sec
indexing index 'product_line_core'...
collected 1229 docs, 0.0 MB
sorted 0.1 Mhits, 100.0% done
total 1229 docs, 32686 bytes
total 0.030 sec, 1081852 bytes/sec, 40677.85 docs/sec
indexing index 'product_line_delta'...
collected 0 docs, 0.0 MB
total 0 docs, 0 bytes
total 0.001 sec, 0 bytes/sec, 0.00 docs/sec
indexing index 'project_core'...
collected 12213 docs, 2.3 MB
sorted 0.4 Mhits, 100.0% done
total 12213 docs, 2335283 bytes
total 7.540 sec, 309716 bytes/sec, 1619.74 docs/sec
indexing index 'project_delta'...
collected 0 docs, 0.0 MB
total 0 docs, 0 bytes
total 0.003 sec, 0 bytes/sec, 0.00 docs/sec
indexing index 'project_partial_match_core'...
collected 12213 docs, 2.1 MB
sorted 8.9 Mhits, 100.0% done
total 12213 docs, 2124984 bytes
total 3.718 sec, 571505 bytes/sec, 3284.63 docs/sec
indexing index 'project_partial_match_delta'...
collected 0 docs, 0.0 MB
total 0 docs, 0 bytes
total 0.003 sec, 0 bytes/sec, 0.00 docs/sec
skipping non-plain index 'contributor'...
skipping non-plain index 'product_line'...
skipping non-plain index 'project'...
total 16 reads, 0.016 sec, 3421.0 kb/call avg, 1.0 msec/call avg
total 178 writes, 0.095 sec, 646.1 kb/call avg, 0.5 msec/call avg
Started searchd successfully (pid: 7696).
```

##### Then upon running the test again, it fails
```shell
production@vagrant:/opt/rails/production/current$ bundle exec rspec spec/controllers/contributors_controller_spec.rb 
** [Raven] Raven 0.13.3 ready to catch errors
Failed to start searchd daemon. Check /opt/rails/production/current/log/test.searchd.log.
..................F........

Failures:

  1) ContributorsController when the user is authenticated GET autocomplete responds with a 200 status code
     Failure/Error: get :autocomplete, :q => "John"
     ThinkingSphinx::ConnectionError:
       Error connecting to Sphinx via the MySQL protocol. Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (111) - SELECT * FROM `contributor_core`, `contributor_delta` WHERE MATCH('John') AND `sphinx_deleted` = 0 LIMIT 0, 25; SHOW META
     # ./app/controllers/contributors_controller.rb:28:in `autocomplete'
     # ./spec/controllers/contributors_controller_spec.rb:186:in `block (4 levels) in <top (required)>'

Finished in 7.47 seconds (files took 18.99 seconds to load)
27 examples, 1 failure

Failed examples:

rspec ./spec/controllers/contributors_controller_spec.rb:185 # ContributorsController when the user is authenticated GET autocomplete responds with a 200 status code
```

##### To avoid this error, I go in and remove this file, then the tests run successfully. 
> Note, I've also had this issue on production, but I haven't been able to reproduce it as well.

```shell
vagrant$/opt/rails/production/current$ ll tmp/binlog/test/
total 4
drwxr-xr-x 1 production production 102 Sep  3 04:31 ./
drwxr-xr-x 1 production production 170 Sep  3 04:12 ../
-rwxr-xr-x 1 production production  11 Sep  1 07:48 binlog.meta*

production@vagrant:/opt/rails/production/current$ rm tmp/binlog/test/binlog.meta 
```

> When I remove that file, I can run the test successfully but note, sometimes the file is the `binlog.lock` file, so its not always the `binlog.meta` file.

##### Here's my `thining_sphinx.yml` file.

```yaml
production:
  address: 127.0.0.1
  mysql41: 9312
  sql_host: myhost
  sql_port: mysql41
  pid_file: /opt/run/production-schedule/searchd.pid
  searchd_file_path: /opt/data/production-schedule/sphinx/data
  indices_location: /opt/data/production-schedule/sphinx/data
  configuration_file: /opt/data/production-schedule/sphinx/production.sphinx.conf
  max_matches: 1000000
  quiet_deltas: true
  mem_limit: 512M

development:
  address: localhost
  mysql41: 9312
  sql_host: localhost
  sql_port: mysql41
  pid_file: /opt/run/production-schedule/searchd.pid
  searchd_file_path: /opt/data/production-schedule/sphinx/data
  indices_location: /opt/data/production-schedule/sphinx/data
  configuration_file: /opt/data/production-schedule/sphinx/development.sphinx.conf
  max_matches: 1000000
  quiet_deltas: true
  mem_limit: 512M


test: &TEST
  mysql41: 9307
  sql_port: mysql41
  searchd_file_path: tmp/sphinx/test/data
  indices_location: tmp/sphinx/test/data
  configuration_file: tmp/sphinx/test.sphinx.conf

cucumber:
  <<: *TEST
```

I'm on Thinking Sphinx 3.1.1 with Sphinx 2.0.4-id64-release (r3135) and Rails 3.2.19.  I thought maybe I can upgrade to thinking sphinx 3.1.4, but due to my use of polymorphic associations I can't do that until I'm on Rails 4.  Any idea why this is happening or how I can avoid this odd behavior?
