### ISSUE TITLE
Partial word search issue, possibly related to german Umlaut

### ISSUE THREAD

**Issue by ncri** [pat/thinking-sphinx#957]
We have a strange partial word search issue:

```ruby
Organization.search("Universitä").map(&:name)
=> ["UniversitätsSpital ... ", "Universitätskliniken ...", "Universitätsspital ...", "... Universität ...", "... Universität ...", "... Universität ...", ...] 
```

That is correct so far, we expect those results due to partial word matches.
However

```ruby
Organization.search("Universität").map(&:name)
=> ["... Universität ...", "... Universität ...", "... Universität ..."] 
```

only gives us results with the full word "Universität" in it, not those with longer words containing "Universität", as in the previous query. With "Universitäts" we don't get those longer word results either:

```ruby
Organization.search("Universitäts").map(&:name)
=> [] 
```

However, when searching for "Universitätss" we suddenly do get the correct results again:

```ruby
Organization.search("Universitätss").map(&:name)
=> ["UniversitätsSpital ... ", "Universitätskliniken ...", "Universitätsspital ..."] 
```

Any idea how to fix this? We need to always get ALL results containing "Universität" when searching for "Universität", as expected.

Here is our config:

```yaml
  version: 2.1.1-beta
  charset_table: "/, ., -, 0..9, A..Z->a..z, _, a..z, U+C0..U+DF->U+E0..U+FF, U+E0..U+FF"
  enable_star: true
  min_infix_len: 3
  dict: keywords
```
