### ISSUE TITLE
Rails 5 - undefined method 'define_index'

### ISSUE THREAD

**Issue by hipertracker** [pat/thinking-sphinx#995]
I am not sure if the project is still alive. I try to upgrade my old Rails3 app to Rails 5. And I have a problem with undefined "define_index" method. :(

```
$ rails ts:configure
Generating configuration to /Users/hipertracker/apps/myapp/config/development.sphinx.conf
rails aborted!
NoMethodError: undefined method `define_index' for Verse (call 'Verse.connection' to establish a connection):Class
Did you mean?  defined_enums
/Users/hipertracker/apps/myapp/app/models/verse.rb:8:in `<class:Verse>'
/Users/hipertracker/apps/myapp/app/models/verse.rb:1:in `<top (required)>'
/Users/hipertracker/apps/myapp/app/indices/verse_index.rb:2:in `block in <top (required)>'
/Users/hipertracker/apps/myapp/bin/rails:9:in `require'
/Users/hipertracker/apps/myapp/bin/rails:9:in `<top (required)>'
/Users/hipertracker/apps/myapp/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => ts:configure
(See full trace by running task with --trace)
```
Gemfile:
```
gem 'rails', '~> 5.0.0'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'thinking-sphinx', github: 'pat/thinking-sphinx'
#...
```

app/models/verse.rb:
```
class Verse < ActiveRecord::Base
  belongs_to :lang
  define_index do
    indexes verse
    has :lang_id
  end
end
```

app/indices/verse_index.rb
```
ThinkingSphinx::Index.define :verse, :with => :active_record do
  indexes text
  has :lang_id
end
```

config/thinking_sphinx.yml
```
development: &shared
  mem_limit: 512M
  min_word_len: 2
  #enable_star: true
  min_infix_len: 3
  html_strip: true  
  charset_table: 0..9, A..Z->a..z, a..z, U+0143->U+0144, U+0104->U+0105, U+0106->U+0107, U+0118->U+0119, U+0141->U+0142, U+00D3->U+00F3, U+015A->U+015B, U+0179->U+017A, U+017B->U+017C, U+0105, U+0107, U+0119, U+0142, U+00F3, U+015B, U+017A, U+017C, U+0144, U+41..U+5a->U+61..U+7a, U+61..U+7a, U+aa, U+b5, U+ba, U+c0..U+d6->U+e0..U+f6, U+d8..U+de->U+f8..U+fe, U+df..U+f6, U+f8..U+ff, U+100..U+12f/2, U+130->U+69, U+131, U+132..U+137/2, U+138, U+139..U+148/2, U+149, U+14a..U+177/2, U+178->U+ff, U+179..U+17e/2, U+17f..U+180, U+181->U+253, U+182..U+185/2, U+186->U+254, U+187..U+188/2, U+189..U+18a->U+256..U+257, U+18b..U+18c/2, U+18d, U+18e->U+1dd, U+18f->U+259, U+190->U+25b, U+191..U+192/2, U+193->U+260, U+194->U+263, U+195, U+196->U+269, U+197->U+268, U+198..U+199/2, U+19a..U+19b, U+19c->U+26f, U+19d->U+272, U+19e, U+19f->U+275, U+1a0..U+1a5/2, U+1a6->U+280, U+1a7..U+1a8/2, U+1a9->U+283, U+1aa..U+1ab, U+1ac..U+1ad/2, U+1ae->U+288, U+1af..U+1b0/2, U+1b1..U+1b2->U+28a..U+28b, U+1b3..U+1b6/2, U+1b7->U+292, U+1b8..U+1b9/2, U+1ba..U+1bb, U+1bc..U+1bd/2, U+1be..U+1c3, U+1c4->U+1c6, U+1c5..U+1c6/2, U+1c7->U+1c9, U+1c8..U+1c9/2, U+1ca->U+1cc, U+1cb..U+1dc/2, U+1dd, U+1de..U+1ef/2, U+1f0, U+1f1->U+1f3, U+1f2..U+1f5/2, U+1f6->U+195, U+1f7->U+1bf, U+1f8..U+21f/2, U+220->U+19e, U+221, U+222..U+233/2, U+234..U+23a, U+23b..U+23c/2, U+23d->U+19a, U+23e..U+240, U+241->U+294, U+250..U+2c1, U+2c6..U+2d1, U+2e0..U+2e4, U+2ee, U+1d00..U+1dbf, U+1e00..U+1e95/2, U+1e96..U+1e9b, U+1ea0..U+1ef9/2, U+37a, U+386..U+389->U+3ac..U+3af, U+38c..U+38e->U+3cc..U+3ce, U+390, U+391..U+3a1->U+3b1..U+3c1, U+3a3..U+3ab->U+3c3..U+3cb, U+3ac..U+3ce, U+3d0..U+3d7, U+3d8..U+3ef/2, U+3f0..U+3f3, U+3f4->U+3b8, U+3f5, U+3f7..U+3f8/2, U+3f9->U+3f2, U+3fa..U+3fb/2, U+3fc..U+3ff, U+400..U+40f->U+450..U+45f, U+410..U+42f->U+430..U+44f, U+430..U+45f, U+460..U+481/2, U+48a..U+4bf/2, U+4c0, U+4c1..U+4ce/2, U+4d0..U+4f9/2, U+500..U+50f/2, U+5D0..U+5EA, U+5F0..U+5F2, U+5BE, U+5C0, U+5C3, U+5F3, U+5F4, U+621..U+63a, U+640..U+64a, U+66e..U+66f, U+671..U+6d3, U+6d5, U+6e5..U+6e6, U+6ee..U+6ef, U+6fa..U+6fc, U+6ff
  indexed_models:
    - Verse
 
test:
  <<: *shared

production:
  <<: *shared

stage:
  <<: *shared
```
